# The PASCAL VOC 2012 dataset in the trainaug variant with instance segmentation masks.
_target_: ocl.datasets.WebdatasetDataModule
train_shards: "${oc.env:DATASET_PREFIX}/navigation5x5/train/shard-{000000..000019}.tar"
train_size: 100000
val_shards: "${oc.env:DATASET_PREFIX}/navigation5x5/val/shard-{000000..000001}.tar"
val_size: 10000
test_shards:
test_size:
use_autopadding: true