_target_: ocl.datasets.WebdatasetDataModule
train_shards: "${oc.env:DATASET_PREFIX}/robosuite-stack/train/shard-{000000..000083}.tar"
train_size: 299878
val_shards: "${oc.env:DATASET_PREFIX}/robosuite-stack/val/shard-{000000..000008}.tar"
val_size: 30000
test_shards:
test_size:
use_autopadding: true