_target_: ocl.datasets.WebdatasetDataModule
train_shards: "${oc.env:DATASET_PREFIX}/vizdoom_defend-line/train/shard-{000000..000191}.tar"
train_size: 299878
val_shards: "${oc.env:DATASET_PREFIX}/vizdoom_defend-line/val/shard-{000000..000019}.tar"
val_size: 30000
test_shards:
test_size:
use_autopadding: true
shuffle_buffer_size: 1000